### ISSUE TITLE
Feature request: Add 'astrox' comp-search folder when generating McXtrace-code

### ISSUE THREAD

**Issue by willend** [PaNOSC-ViNYL/McStasScript#67]
The McXtrace software has a special sub-category for the so-called "AstroX" components for X-ray telescopes.

Please add 'astrox' to the relevant search path in `mcstasscript/helper/component_reader`

**Comment by willend** [comment]
(It would also be nice if the print-statement that fails to find components refers to McXtrace in such cases - see below for an example - generated via the mcxtrace-pygen tool from CXO.instr of the mccode-3 branch)

```
cxtrace-3.x-dev env mcx $ python3 CXO_generated.py
Traceback (most recent call last):
 File "/home/nexmap/pkwi/tmp/mcx/CXO_generated.py", line 199, in <module>
  sh1_p = instr.add_component('sh1_p','Shell_p', AT=['0', '0', '0'], AT_RELATIVE='optics_centre', ROTATED=['0.0', '0.0', '0.0'], ROTATED_RELATIVE='optics_centre')
 File "/home/nexmap/pkwi/McXtrace/mcxtrace/3.x-dev/miniconda3/lib/python3.10/site-packages/mcstasscript/interface/instr.py", line 1262, in add_component
  new_component = self._create_component_instance(name, component_name,
 File "/home/nexmap/pkwi/McXtrace/mcxtrace/3.x-dev/miniconda3/lib/python3.10/site-packages/mcstasscript/interface/instr.py", line 1161, in _create_component_instance
  comp_info = self.component_reader.read_name(component_name)
 File "/home/nexmap/pkwi/McXtrace/mcxtrace/3.x-dev/miniconda3/lib/python3.10/site-packages/mcstasscript/helper/component_reader.py", line 239, in read_name
  raise NameError("No component named "
NameError: No component named Shell_p in McStas installation or current work directory.
```

**Comment by mads-bertelsen** [comment]
Great point, astrox was added to the list of possible folders with components in McCode installations. On master, included in next pip release shortly.
